### ISSUE TITLE
Background color is wrong for Ruby code in HAML 

### ISSUE THREAD

**Issue by zumbrunnen** [tdm00/sublime-theme-railscasts#4]
In Sublime Text 3, I have a slightly darker background for Ruby code in HAML files:
![screen shot 2013-05-31 at 15 32 41](https://f.cloud.github.com/assets/3499909/591040/2ef20d94-c9f8-11e2-958b-90cfb74110b5.png)

Removing those lines fixed this issue for me:

``` diff
@@ -28,11 +28,6 @@
       <string>ERB</string>
       <key>scope</key>
       <string>source.ruby.embedded, source.ruby.rails.embedded</string>
-      <key>settings</key>
-      <dict>
-        <key>background</key>
-        <string>#1F1F1F</string>
-      </dict>
     </dict>
     <dict>
       <key>name</key>
```

Also, I could set the color to #282828.

I'm not sure if this conflicts with Sublime Text 2. But I'll file a pull request, if you want.

**Comment by tdm00** [comment]
David,

Thanks for opening this issue.  I haven't used Sublime Text 3 beta yet, I
haven't seen the value is moving from ST2 yet.  Please send a PR and I'll
try testing it.

On Fri, May 31, 2013 at 9:52 AM, David Zumbrunnen
notifications@github.comwrote:

> In Sublime Text 3, I have a slightly darker background for Ruby code in
> HAML files:
> [image: screen shot 2013-05-31 at 15 32 41]https://f.cloud.github.com/assets/3499909/591040/2ef20d94-c9f8-11e2-958b-90cfb74110b5.png
> 
> Removing those lines fixes this issue for me:
> 
> @@ -28,11 +28,6 @@
>        <string>ERB</string>
>        <key>scope</key>
>        <string>source.ruby.embedded, source.ruby.rails.embedded</string>\-      <key>settings</key>\-      <dict>\-        <key>background</key>\-        <string>#1F1F1F</string>\-      </dict>
>      </dict>
>      <dict>
>        <key>name</key>
> 
> Also, I could set the color to #282828.
> 
> I'm not sure if this conflicts with Sublime Text 2. But I'll file a pull
> request, if you want.
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/tdm00/sublime-theme-railscasts/issues/4
> .

## 

_Troy Murray_

**Comment by zumbrunnen** [comment]
Hi Troy

Thanks for the super-quick reply. I've sent you the PR.

**Comment by tdm00** [comment]
No problem.  I'll see what I can do to get it tested today.

On Fri, May 31, 2013 at 9:55 AM, David Zumbrunnen
notifications@github.comwrote:

> Hi Troy
> 
> Thanks for the super-quick reply. I've sent you the PR (although I didn't
> manage to reference this issue [image: :smile:] )
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/tdm00/sublime-theme-railscasts/issues/4#issuecomment-18746135
> .

## 

_Troy Murray_
