### ISSUE TITLE
Sublime text 3 Compatibilty

### ISSUE THREAD

**Issue by cabhishek** [tdm00/sublime-theme-railscasts#6]
Unable to install via Package manager on latest ST3 build 3047. This theme is not available when I try to search it in via Package Manager,

**Comment by tdm00** [comment]
@cabhishek thanks for contacting me about this.  Is there a chance you already have the theme installed, which would prevent it from being displayed in the list.  I just performed a fresh install of Sublime Text 3 (I'm not using it yet), installed the Package Control and was able to install the theme from the Package Control list.

Let me know.

**Comment by cabhishek** [comment]
@tdm00 Yes that was the case. Sorry to bother you. And please close this issue :)

**Comment by tdm00** [comment]
No bug and no problem, have a nice day!

On Tue, Aug 13, 2013 at 3:34 PM, Abhishek notifications@github.com wrote:

> @tdm00 https://github.com/tdm00 Yes that was the case. Sorry to bother
> you. And please close this bug :)
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/tdm00/sublime-theme-railscasts/issues/6#issuecomment-22591176
> .

## 

_Troy Murray_
